apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "service.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive
            port: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
        env:
        - name: PORT
          value: "8080"
        - name: SERVICE_NAME
          value: "{{ template "service.name" . }}"        
        - name: SERVICE_SECRET
          value: "{{ template "service.name" . }}-secret"
        - name: DATABASE_NAME
          value: "{{ .Values.db.name }}"
        - name: DATABASE_USER
          value: "{{ .Values.db.user }}"
        - name: DATABASE_PASSWORD
          value: "{{ .Values.db.password }}"