
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm
    repoURL: {{ index .Values.spec.services "ads-service" "source" }}
    targetRevision: {{ index .Values.spec.services "ads-service" "revision" }}