
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: eu.gcr.io/humanitec-demo-1/store-ads-service
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    path: ads-service
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}